require:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: "indented"

Metrics/ParameterLists:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
